### PR TITLE
Fix manifest warnings

### PR DESCRIPTION
**Pull request by paultcochrane**

### CODE REVIEW

**Comment by paultcochrane** [comment]
Sh*t!  It looks like I mistakenly hit Enter before I could give this PR a proper description.  Sorry!  I noticed that an extra file was mentioned in the MANIFEST and that the README filename needed updating.  This PR corrects those two issues.

**Comment by paultcochrane** [comment]
Awesome! Many thanks for merging these patches :-)

**Comment by karpet** [comment]
thank *you* for taking the time! Are you an actual user of this module, or taking up the perl pull request challenge? or both?

**Comment by paultcochrane** [comment]
Heh, no worries :-)  I'm doing the pull request challenge.  Sorry for not making this clear up front; I tend to make the assumption that people don't mind pull requests anyway, so I've stopped mentioning it in my initial PRs.

**Pull request merged**
